name: Test Coverage

on:
  - push
  - pull_request

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  DJANGO_SETTINGS_MODULE: task_manager.settings

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv sync
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: uv run python3 -m pytest --cov=task_manager --cov-report=xml:coverage.xml
          debug: true



