name: Test Coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage

    - name: Run tests and generate coverage report
      run: |
        coverage run -m pytest
        coverage xml -o coverage.xml

    - name: Install CodeClimate Test Reporter
      run: curl -L https://github.com/codeclimate/test-reporter/releases/download/v0.11.4/codeclimate-test-reporter-linux-amd64 > ./cc-test-reporter
      shell: bash

    - name: Set permissions for CodeClimate Test Reporter
      run: chmod +x ./cc-test-reporter

    - name: Upload coverage to CodeClimate
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      run: ./cc-test-reporter format-coverage --input-type coverage.py coverage.xml
      shell: bash