name: Django CI

on: [push, pull_request]

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  DJANGO_SETTINGS_MODULE: task_manager.settings

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage pytest pytest-django
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ]; then pip install -e .; fi

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests with coverage
        run: |
          mkdir -p reports
          python -m coverage run --source=task_manager,tests --omit=*/migrations/* -m pytest -v
          python -m coverage lcov -o reports/lcov.info
          python -m coverage report

      - name: Upload to QLty
        uses: qltysh/qlty-action/coverage@v1
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: reports/lcov.info